
spring:
  h2:
    console:
      enabled: true
      path: /gadget-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:gadget-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: gadgetadmin
    password: gadgetpwd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true